/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-08 05:15:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1686639167910L));
    _jspx_dependants.put("/member/../include/header.jsp", Long.valueOf(1686741835886L));
    _jspx_dependants.put("/member/../include/footer.jsp", Long.valueOf(1686639167953L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/course/JSPJSP/apache-tomcat-9.0.75/wtpwebapps/adsf/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>CUCUMART</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/20962f3e4b.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/product.css\">\r\n");
      out.write("    <!--\r\n");
      out.write("        날짜 : 2022/12/06\r\n");
      out.write("        이름 : 박종협\r\n");
      out.write("        내용 : Kmarket main layout\r\n");
      out.write("    -->\r\n");
      out.write("    <style>\r\n");
      out.write("		.rainbow {\r\n");
      out.write("		  background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);\r\n");
      out.write("		  -webkit-background-clip: text;\r\n");
      out.write("		  -webkit-text-fill-color: transparent;\r\n");
      out.write("		  animation: sparkling 2s linear infinite;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes sparkling {\r\n");
      out.write("		  0% {\r\n");
      out.write("		    background-position: 0% 50%;\r\n");
      out.write("		    filter: hue-rotate(0deg);\r\n");
      out.write("		  }\r\n");
      out.write("		  100% {\r\n");
      out.write("		    background-position: 100% 50%;\r\n");
      out.write("		    filter: hue-rotate(360deg);\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("		  #product > .view > article {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }        \r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > div {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 50%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .image > img { width: 100%; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary > nav {\r\n");
      out.write("            border-bottom: 1px solid #eaeaea;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary > nav > h1 {\r\n");
      out.write("            float: left;\r\n");
      out.write("            color: #0231a6;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.5em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary > nav > h2 {\r\n");
      out.write("            float: right;\r\n");
      out.write("            color: #777;\r\n");
      out.write("            margin-top: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary > nav > h3 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #1e2732;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary > nav > p {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #474747;\r\n");
      out.write("            line-height: 36px;\r\n");
      out.write("            letter-spacing: -1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary > nav:nth-child(2) > .rating > a {\r\n");
      out.write("            color: #346aff;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .org_price > del {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .org_price > del::after { content: \"원\"; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .org_price > span {\r\n");
      out.write("            color: #eb000a;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin-left: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .org_price > span::after { content: \"↓\"; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .dis_price > ins {\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .dis_price > ins::after { content: \"원\"; }\r\n");
      out.write("        #product > .view > .info > .summary .delivery {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #2e8de5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .origin {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .arrival {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        #product > .view > .info > .summary .desc {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .card > i {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 18px;\r\n");
      out.write("            top: 4px;\r\n");
      out.write("            font-size: 0;\r\n");
      out.write("            vertical-align: text-top;\r\n");
      out.write("            margin-right: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .cardfree > i { background-position: -126px 0; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .cardadd > i { background-position: -51px -21px; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .banner { width: 100%; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .count {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .count > button {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 21px;\r\n");
      out.write("            height: 21px;\r\n");
      out.write("            background-image: url(./img/ico_sprites.png);\r\n");
      out.write("            font-size: 0;\r\n");
      out.write("            background-color: transparent;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .count > input[name=num] {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 30px;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 21px;\r\n");
      out.write("            border: 1px solid #ececec;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .count > .decrease {\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            background-position: 0px -74px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .count > .increase {\r\n");
      out.write("            left: 70px;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            background-position: -48px -74px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .total {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            margin-top: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .total > span {\r\n");
      out.write("            float: right;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            line-height: 38px;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #000;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            letter-spacing: -0.5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .total > span::after { content: \"원\";}\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .total > em {\r\n");
      out.write("            float: right;\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            padding: 10px 0 0;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            line-height: 22px;\r\n");
      out.write("            color: #5e636d;\r\n");
      out.write("            letter-spacing: -1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .button {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            margin-top: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .button > input {\r\n");
      out.write("            float: left;\r\n");
      out.write("            width: 49%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            margin: 2px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .button > .cart {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 1px solid #d9d9d9;\r\n");
      out.write("            color: #233594;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .info > .summary .button > .order {\r\n");
      out.write("            background: #2e8de5;\r\n");
      out.write("            border: 1px solid #217fd7;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > .paging > .num > a.on {\r\n");
      out.write("            color: #fe434c;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > article > nav {\r\n");
      out.write("            border-bottom: 1px solid #a4a9b0;\r\n");
      out.write("            padding: 6px 0;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > article > nav > p {\r\n");
      out.write("            float: left;\r\n");
      out.write("            color: #777;\r\n");
      out.write("            margin-top: 6px;\r\n");
      out.write("            margin-left: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > article > nav > h1 {\r\n");
      out.write("            float: left;\r\n");
      out.write("            color: #1e2732;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.5em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .notice > table { width: 100%; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .notice > table:nth-of-type(2) { border-top: 1px solid #ececec; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .notice > table tr > td {\r\n");
      out.write("             padding: 5px 0 6px 21px;\r\n");
      out.write("             font-size: 14px;\r\n");
      out.write("             color: #777;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .notice > table tr > td:nth-child(1) { width: 20%; color: #222; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul > li {\r\n");
      out.write("            padding-top: 16px;\r\n");
      out.write("            border-bottom: 1px solid #ececec;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul > li > div { overflow: hidden; }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul > li > div > span {\r\n");
      out.write("            float: right;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul > li > div >  h5 { float: left; }\r\n");
      out.write("\r\n");
      out.write("        #product h5.rating {\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            font-size: 0px;\r\n");
      out.write("            background-image: url(../img/ico_rating_star.png);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            /*  background-position: 36px 0px;*/\r\n");
      out.write("            text-indent: 86px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul > li > h3 {\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-top: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > ul > li > p {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            line-height: 19px;\r\n");
      out.write("            word-break: break-all;\r\n");
      out.write("            word-wrap: break-word;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > .paging {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 30px 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .notice > .notice {\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            padding: 21px 26px 20px 19px;\r\n");
      out.write("            line-height: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #757c8a;\r\n");
      out.write("            background: #fafafa;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            white-space: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review >.paging > span > a { \r\n");
      out.write("            color: #777;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            letter-spacing: -1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #product > .view > .review > .paging > .num > a {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            min-width: 14px;\r\n");
      out.write("            margin: 0 2px;\r\n");
      out.write("            padding: 8px 9px;\r\n");
      out.write("            border: 1px solid #c4c4c4;\r\n");
      out.write("            color: #000;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        #product > .view > .review > .paging > .num > a.on {\r\n");
      out.write("            color: #fe434c;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        #searchInput {\r\n");
      out.write("    animation: blink-caret 3s step-end infinite;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  @keyframes blink-caret {\r\n");
      out.write("    from, to {\r\n");
      out.write("      border-color: transparent;\r\n");
      out.write("    }\r\n");
      out.write("    50% {\r\n");
      out.write("      border-color: black;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("  	window.onload = function() {\r\n");
      out.write("    	var searchInput = document.getElementById('searchInput');\r\n");
      out.write("    	searchInput.focus();\r\n");
      out.write("  	};\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div class=\"top\">\r\n");
      out.write("				<div>\r\n");
      out.write("						");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                   		");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /member/../include/header.jsp(395,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member_id != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("                   		");
                  if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
                    return;
                  out.write("\r\n");
                  out.write("						\r\n");
                  out.write("                        <a href=\"");
                  out.print(request.getContextPath() );
                  out.write("/member/member_mypage.member\" style=\"color:blue\">마이페이지</a>\r\n");
                  out.write("                        <a href=\"");
                  out.print(request.getContextPath() );
                  out.write("/member/member_logout.member\" style=\"color:red\">로그아웃</a>\r\n");
                  out.write("                        <a href=\"");
                  out.print(request.getContextPath() );
                  out.write("/product/product_addcart.pd\" style=\"color:black\" class=\"rainbow\" > <i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i> 장바구니</a>\r\n");
                  out.write("                    ");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("                    ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f1_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("                        <a href=\"");
                  out.print(request.getContextPath() );
                  out.write("/member/member_login.member\" style=\"color:blue\">로그인</a>\r\n");
                  out.write("                        <a href=\"");
                  out.print(request.getContextPath() );
                  out.write("/member/member_join.member\" style=\"color:red\">회원가입</a>\r\n");
                  out.write("                    ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
              _jspx_th_c_005fotherwise_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
            }
            out.write("\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"logo\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/home.member\"> <img src=\"../img/JJAPANG.jpg\" width=\"300px\"\r\n");
      out.write("						alt=\"헤더로고\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<form action=\"#\">\r\n");
      out.write("						 <input type=\"text\" name=\"search\" id=\"searchInput\" value=\"세상에 이런 쇼핑몰은 없었다! 짭팡!\" style = \"color:lightgrey\">\r\n");
      out.write("						  <button>\r\n");
      out.write("						    <i class=\"fa fa-search\" aria-hidden=\"true\"></i>\r\n");
      out.write("						  </button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"menu\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/product/product_list.pd\">히트상품</a></li>\r\n");
      out.write("						<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/product/product_list.pd\">추천상품</a></li>\r\n");
      out.write("						<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/product/product_list.pd\">최신상품</a></li>\r\n");
      out.write("						<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/product/product_list.pd\">인기상품</a></li>\r\n");
      out.write("						<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/product/product_list.pd\">할인상품</a></li>\r\n");
      out.write("						<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/product/product_list.pd\" style=\"color:black\" class=\"rainbow\" >짭팡상품!</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">쿠폰존</a></li>\r\n");
      out.write("						<li><a href=\"#\">개인결제</a></li>\r\n");
      out.write("						<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("		<button type=\"button\" id=\"top\">상단이동</button>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<section>\r\n");
      out.write("			<head>\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table {\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	border: 3px solid skyblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	border: 1px solid skyblue\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("	background-color: skyblue\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("					<br> <br> <b><font size=\"6\" color=\"gray\">회원가입</font></b>\r\n");
      out.write("					<br> <br> <br>\r\n");
      out.write("			<form action=\"joinForm.member\" method=\"post\">\r\n");
      out.write("				<table border=\"1\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>아이디</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"m_id\" required=\"required\"\r\n");
      out.write("							pattern=\"\\w{4,}\"></td>\r\n");
      out.write("					<tr />\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>비밀번호</td>\r\n");
      out.write("						<td><input type=\"password\" name=\"m_pw\" required=\"required\"></td>\r\n");
      out.write("					<tr />\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>이름</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"m_name\" required=\"required\"></td>\r\n");
      out.write("					<tr />\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>이메일</td>\r\n");
      out.write("						<td><input type=\"email\" name=\"m_email\"></td>\r\n");
      out.write("					<tr />\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>주소</td>\r\n");
      out.write("						<td><input type=\"text\" name=\"m_adress\" required=\"required\"></td>\r\n");
      out.write("					<tr />\r\n");
      out.write("					<td>회원타입</td>\r\n");
      out.write("	 				<td> \r\n");
      out.write("	 				<input type=\"radio\" name = \"m_type\" value = \"B\" checked=\"checked\">구매자\r\n");
      out.write("	 				<input type=\"radio\" name = \"m_type\" value = \"S\">판매자\r\n");
      out.write(" 					</td>\r\n");
      out.write("					\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("				<div style=\"color: orange;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<input type=\"submit\" value=\"가입\"> <input type=\"reset\"\r\n");
      out.write("					value=\"정보초기화\">\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".footer-text {\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-text span {\r\n");
      out.write("    color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                <p class=\"footer-text\">Copyright &copy; By <span>'중앙산'</span> 2023.06.14</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("                   		\r\n");
          out.write("                   		");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                   		");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /member/../include/header.jsp(397,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member_type != 'B' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" (판매자)");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" (구매자)");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
